---
  - name: enable web server
    tasks:
  - name: Install apache httpd  (state=present is optional)
    apt:
      name: apache2
      state: present
  - name: create a welcome page
    copy:
      content: "welcome to the webserver\n"
      dest: /var/www/html/index.html
  - name: enable webserver
    service: 
      name: apache2
      state: started
      enabled: true

