Description: >
    Mario Rodriguez - AWS portion of CircleCI and AWS pipeline

Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  
  UbuntuImageId:
    Description: Region specific Ubuntu 20 image
    Type: String
    Default: ami-06e54d05255faf8f6

Resources:

  WebSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh/http to webserver
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp 
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp 
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp 
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
        ImageId: 
          Ref: UbuntuImageId
        KeyName: that-one
        SubnetId: 
          Fn::ImportValue:
            !Sub "${EnvironmentName}-PUB-SN"
        InstanceType: t2.nano
        SecurityGroupIds:
        - !GetAtt WebSecGroup.GroupId
        BlockDeviceMappings:
        - DeviceName: "/dev/sdk"
          Ebs:
            VolumeSize: 10
        Tags:
          - Key: Name
            Value: AnsibleTesting
