version: 2.1

workflows:
  deploy_workflow:
    jobs:
      - deploy_infra:
          context: 
            - aws
jobs:
  deploy_infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: aws cloudformation deploy --stack-name $network-stack-name --template-file file://$network-stack-template --parameter-overrides file://$network-stack-params
      - run: aws cloudformation wait stack-create-complete --stack-name $network-stack-name
        #- run: aws cloudformation deploy --stack-name <<parameters.server-stack-name>> --template-file file://<<parameters.server-stack-template>> --parameter-overrides file://<<parameters.server-stack-params>>
        #- run: aws cloudformation wait stack-create-complete --stack-name <<parameters.server-stack-name>>

