version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.0

jobs:
  deploy_network:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: oregon
      - run: create.sh AWSLearnNetwork network.yml network-parameters.json
  wait_for_network:
    docker:
      - image: cimg/base:stable
    steps:
      - run: sleep 5m
  deploy_server:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: oregon
      - run: create.sh AWSLearnServer server.yml server-parameters.json


workflows:
  version: 2
  aws-cli:
    jobs:
      - deploy_network:
          context: aws
      - wait_for_network:
          requires:
            - deploy_network
      - deploy_server:
          context: aws
          requires:
            - wait_for_network

