version: 2.1

jobs:
  deploy_infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
          name: Network Tier Deploy
          command: |
            echo $NETWORK_STACK_NAME
            #aws cloudformation deploy --stack-name $NETWORK_STACK_NAME --template-file file://$NETWORK_STACK_TEMPLATE --parameter-overrides file://$NETWORK_STACK_PARAMS
            #aws cloudformation wait stack-create-complete --stack-name $NETWORK_STACK_NAME
            #aws cloudformation deploy --stack-name $SERVER_STACK_NAME --template-file file://$SERVER_STACK_TEMPLATE --parameter-overrides file://$SERVER_STACK_PARAMS
            #aws cloudformation wait stack-create-complete --stack-name $SERVER_STACK_NAME

workflows:
  deploy_workflow:
    jobs:
      - deploy_infra:
          context: aws
