version: 2.1

workflows:
  deploy_workflow:
    jobs:
      - deploy_network_tier:
          context: aws
      - deploy_server_tier:
          context: aws
          requires:
            - deploy_network_tier

jobs:
  deploy_network_tier:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Network Infra Deploy"
          command:
            aws cloudformation deploy --stack-name $NETWORK_STACK_NAME --template-file $NETWORK_STACK_TEMPLATE --parameter-overrides file://$NETWORK_STACK_PARAMS            
  deploy_server_tier:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Server Infra Deploy"
          command:
            aws cloudformation deploy --stack-name $SERVER_STACK_NAME --template-file $SERVER_STACK_TEMPLATE --parameter-overrides file://$SERVER_STACK_PARAMS --capabilities CAPABILITY_IAM
