version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.0

jobs:
  deploy_infra:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: oregon
      - run: aws ec2 describe-instances

workflows:
  version: 2
  aws-cli:
    jobs:
      - deploy_infra:
          context: aws
